import React from "react";
import { Link } from "react-router-dom";
import classes from "./TermsOfuse.module.css";
import Footer from "../../components/footer/Footer";
const TermsOfUse = () => {
  return (
    <>
      <div className={classes.mainLayout}>
        <div className={classes.subLayout} id={classes.justify}>
          <div className={classes.content}>
            <div className={classes.detailedContent}>
              <h1 className={classes.headerText}>
                TERMS OF USE - DIGISTORE
                <span className={classes.headerTextSpan}> PAY</span> APPLICATION
              </h1>
              <div>
                <h4>Introduction:</h4>
                <p id={classes.justify}>
                  This document is an electronic record in terms of Information
                  Technology Act, 2000 and rules there under as applicable. This
                  electronic record is generated by a computer system and does
                  not require any physical or DiGital signatures. 
                  <br />
                  This document is published in accordance with the provisions
                  of Rule 3 (1) of the Information Technology (Intermediaries
                  guidelines) Rules, 2011 that require publishing the rules and
                  regulations, privacy policy and terms of use for access or
                  usage of this mobile application ("App"). 
                  <br />
                  The Terms and Conditions (T&C) contained herein along with the
                  Privacy Policy, Customer Credit Terms of Use & Cancellation &
                  Refund Policies constitutes a legally binding Agreement
                  between the User & DiGi Suvidha Private Limited. “DiGistore
                  Pay” web application is owned and controlled by DiGi Suvidha
                  Private Limited. User is hereinafter referred to as “DiGistore
                  Pay User”/ “You”/ “Your”.
                  <br />
                  These terms of use ("Terms"), including the various policies
                  incorporated by reference in these Terms, govern your access
                  to and use of this App, its website and the underlying
                  services provided by us through the App, including our SMS,
                  APIs, email notifications, applications, buttons, widgets,
                  ads, commerce services, and our other covered services that
                  may link to these Terms (collectively, the "Services"), and
                  any information, text, graphics, photos or other materials
                  uploaded, downloaded or appearing on or as a part of the
                  Services (collectively referred to as "Content"). Your access
                  to and use of the Services, however accessed, constitutes your
                  agreement to be bound by these Terms, which establishes a
                  contractual relationship between You and DiGi Suvidha. When
                  You use any of the Services provided by Us through the
                  App/website, you will be subject to the rules, guidelines,
                  policies, terms, and conditions applicable to such Service,
                  and they shall be deemed to be incorporated into and shall
                  apply in addition to these Terms. If you transact on the App
                  or our website, you shall be subject to the policies that are
                  applicable to the App/Website for such transactions. 
                  <br />
                  By downloading or using the app, these terms will
                  automatically apply to you - you should make sure therefore
                  that you read them carefully before using the app. If you do
                  not agree to these App Terms, you must immediately uninstall
                  the App and discontinue its use. You shall be a person of
                  legal age and not barred to execute an Agreement as per the
                  laws of India at the time of sign-up. If you have any
                  questions regarding our App, you can email us at
                  <Link className={classes.linkTags}>
                    {" "}
                    info@digistorepay.com
                  </Link>
                  .
                </p>
              </div>
              <div>
                <h4>Changes:</h4>
                <p id={classes.justify}>
                  DiGi Suvidha Private Limited, reserves the right to suspend /
                  cancel, or discontinue any or all accounts, products or
                  service at any time without notice, make modifications and/or
                  alterations in any or all of the content, products and
                  services contained on the App without prior notice. 
                </p>
              </div>
              <div>
                <h4>Definitions:</h4>
                <p id={classes.justify}>
                  <strong>"Agreement" </strong>means the Terms and Conditions
                  (T&C) contained herein along with the Privacy Policy and Terms
                  of Use, including other T&C on the App/Website of DiGi Suvidha
                  under the brand DiGistore Pay. It will also include references
                  to this Agreement as and when amended, notated, supplemented,
                  varied, or replaced. 
                  <br />
                  <strong>"Mobile App" </strong>or{" "}
                  <strong>"Digistore Pay" </strong>includes all online platforms
                  (including Digistore Pay Mobile Applications and Browser
                  Extensions) owned and/or operated by DiGi Suvidha Private
                  Limited, providing users with access to a range of financial
                  and service-based offerings. These platforms enable users to
                  manage and complete various transactions, bookings, and
                  filings, both online and offline.
                  <br />
                  <strong>"User/You/ Your" </strong>refers to any person or
                  entity using or accessing DiGi Suvidha's services, including
                  franchises, customers, and other individuals engaging in
                  transactions, accessing information, or participating in other
                  activities via the App. 
                  <br />
                  <strong>"We/Us/Our" </strong>refers to DiGi Suvidha Private
                  Limited, its subsidiaries, and affiliates providing services
                  through the mobile and web applications.
                </p>
              </div>
              <div>
                <h4>The Services:</h4>
                <p id={classes.justify}>
                  This Mobile App is solely a platform for interaction and
                  facilitation of legally recognized transactions between the
                  franchise and potential customers. Digistore Pay acts merely
                  as a facilitator for such transactions, with all commercial
                  and contractual terms being offered independently by the
                  franchises or affiliates and agreed to by users or buyers
                  independently. Digistore Pay assumes no liability for
                  deficiencies in services, quality of goods and services, or
                  any issues arising from or related to such transactions. The
                  commercial and contractual terms include, without limitation,
                  price, fees, timelines, mode of service delivery, warranties
                  related to products and services (including post-sale
                  services), etc., over which the franchise/seller has complete
                  control. These terms may be subject to change, and Digistore
                  Pay has no control over them.
                  <br />
                  Digistore Pay reserves the right to reduce or remove the
                  available balance without prior notice or suspend, block, or
                  delete the User's account at its sole discretion. We may also
                  assign an expiry date to any earned value-back vouchers,
                  cashback, or bonuses, without prior notice, and reduce or
                  remove the available vouchers or points if they are not used
                  before the expiry date.
                  <br />
                  You further agree and acknowledge that the App is not involved
                  in the sale or purchase of goods, products, or services and
                  cannot warrant the quality or merchantability of any goods
                  purchased using deals, coupons, or vouchers. Digistore Pay is
                  solely a facilitator and intermediary and does not participate
                  in or control any transactions between the Vendor/Seller and
                  the User/Customer/Buyer. Digistore Pay is neither responsible
                  nor liable for mediating or resolving any disputes or
                  disagreements between Users and Vendors.
                  <br />
                  Digistore Pay shall neither be liable nor responsible for any
                  actions or inactions of Vendors, Merchants, or Sellers, or for
                  any breach of conditions, representations, or warranties by
                  the merchant or manufacturer of the products. Digistore Pay
                  does not sell or retail any products and does not ensure that
                  Users fulfill their obligations in transactions concluded on
                  this App. Additionally, Digistore Pay expressly disclaims any
                  warranties or representations, whether express or implied,
                  regarding the quality, safety, merchantability, fitness for a
                  particular purpose, or legality of the products listed and
                  transacted on the App.
                  <br />
                  You further agree and undertake that you are accessing the
                  DiGi Suvidha Services available on this App and engaging in
                  transactions at your own risk. You are responsible for
                  exercising your best and prudent judgment before entering into
                  any transaction through this App.
                  <br />
                  Digistore Pay accepts no liability for any errors or
                  omissions, whether caused by itself or third parties.
                  Digistore Pay shall not be responsible for any non-performance
                  or breach of any contract entered into between Users.
                  <br />
                  The agreement between Digistore Pay User and Digistore Pay is
                  subject to the following terms and conditions: 
                  <ul id={classes.justify}>
                    <li>
                      User Certification: You certify that you are at least 18
                      years of age and are legally capable of entering into
                      agreements.
                    </li>
                    <li>
                      Supersession of Terms: These terms and conditions
                      supersede all previous representations, understandings, or
                      agreements and shall prevail over any other terms from
                      orders or logins through other related IDs. By using
                      Digistore Pay's services, you agree to be bound by these
                      Terms and Conditions.
                    </li>
                    <li>
                      Pricing: All prices, unless indicated otherwise, are in
                      Indian Rupees.
                    </li>
                    <li>
                      Transaction Obligation: By indicating acceptance to
                      purchase any product or service offered on the App, you
                      are obligated to complete the transaction after making
                      payment. You are prohibited from indicating acceptance for
                      transactions you do not intend to complete.
                    </li>
                    <li>
                      Liability and Warranties: Digistore Pay is not responsible
                      for non-performance or breach of any contract between you
                      and the Vendor/Merchant. Digistore Pay does not make any
                      representation or warranty regarding the quality, worth,
                      marketability, or other attributes of the products or
                      services offered on the App.
                    </li>
                    <li>
                      Credit Card Use: In credit card transactions, you must use
                      your own credit card. Digistore Pay will not be liable for
                      any credit card fraud. The responsibility for fraudulent
                      use lies with you, and you must prove otherwise if
                      disputed. Digistore Pay monitors transactions for
                      fraudulent activity and reserves the right to cancel
                      orders if suspicious activity is detected.
                    </li>
                    <li>
                      Lawful Use: You agree to use Digistore Pay's services, and
                      those of its affiliates and partners, for lawful purposes
                      only.
                    </li>
                    <li>
                      Authenticity of Information: You agree to provide accurate
                      and truthful information. Digistore Pay reserves the right
                      to verify and validate the information provided and may
                      request documents for this purpose. If your details are
                      found to be false or inaccurate, Digistore Pay may reject
                      your registration and restrict your access to its services
                      without prior notice.
                    </li>
                    <li>
                      Damage Disclaimer: Digistore Pay is not responsible for
                      any damage suffered by users from using the services on
                      the App. This includes, but is not limited to, loss of
                      revenue/data due to delays, non-deliveries, missed
                      deliveries, or service interruptions. This disclaimer also
                      applies to damages or injuries resulting from performance
                      failures, errors, omissions, interruptions, computer
                      viruses, communication failures, theft, or unauthorized
                      access.
                    </li>
                    <li>
                      Cancellation Policy: Cancellation requests may not be
                      allowed, depending on the specific terms and conditions of
                      the purchased product or service. Refunds for canceled
                      orders will be processed as per the payment mode selected
                      by the customer.
                    </li>
                    <li>
                      Authorization Decline: Digistore Pay is not liable for any
                      loss or damage arising from the decline of authorization
                      for any transaction due to the cardholder exceeding the
                      pre-set limit agreed upon with the acquiring bank.
                    </li>
                    <li>
                      Transactional Communication: Digistore Pay reserves the
                      right to send transactional emails and SMS messages
                      related to your order. By providing your mobile number,
                      you consent to receive calls/SMS from DiGi Suvidha or its
                      representatives, even if you are registered on Do Not
                      Disturb (DND) with your telecom service provider.
                    </li>
                    <li>
                      Clarification Calls: You agree to receive calls from
                      Digistore Pay and its agents, merchants, or courier
                      partners seeking clarification or information regarding
                      your order, and acknowledge that Digistore Pay is not
                      liable in this regard.
                    </li>
                  </ul>
                </p>
              </div>
              <div>
                <h4>Use Of Contents:</h4>
                <p id={classes.justify}>
                  The contents of the Digistore Pay Software/application/website
                  can be viewed and used on your mobile device for purchasing
                  various types of goods and services through designated mediums
                  provided by Digistore Pay and configured to the content
                  published or broadcasted by Digistore Pay via its Software.
                  You grant DiGi Suvidha the right to sub-license these rights
                  and to take action for any infringement of these rights.
                  Digistore Pay reserves the right to edit or remove any
                  material submitted to this App, stored on our servers, or
                  hosted or published on this App.
                  <br />
                  Notwithstanding any other provisions, you agree and
                  acknowledge that Digistore Pay may have acquired content under
                  valid licenses. If the delivery of the content and/or the
                  Software, or any part thereof, is halted due to the
                  termination of such license agreements with third parties,
                  Digistore Pay will cease the use of such content, and you will
                  not raise any objections or claim any loss from Digistore Pay.
                  <br />
                  Digistore Pay may upload content on behalf of third parties
                  after collecting and verifying the information if deemed
                  necessary. However, Digistore Pay cannot be held liable for
                  any false or misleading information.
                  <br />
                  Users of our App may post reviews, comments, and other
                  content, provided that such content is not illegal, obscene,
                  abusive, threatening, defamatory, invasive of privacy,
                  infringing on intellectual property rights, objectionable, or
                  harmful to third parties. Additionally, content should not
                  contain software viruses, political campaigning, commercial
                  solicitation, chain letters, mass mailings, or any form of
                  "spam." If a user posts content using a false email address,
                  impersonates any person or entity, or misleads about the
                  origin of any content, Digistore Pay reserves the right to
                  remove, refuse, delete, or edit any such content and may
                  terminate the user's access to or use of our website.
                </p>
              </div>
              <div>
                <h4>Links:</h4>
                <p id={classes.justify}>
                  The Services may contain links to third-party websites or
                  resources. You acknowledge and agree that Digistore Pay is not
                  responsible or liable for: (i) the availability or accuracy of
                  such websites or resources; or (ii) the content, products, or
                  services on or available from such websites or resources.
                  Links to these websites or resources do not imply any
                  endorsement by Digistore Pay of the websites, resources, or
                  the content, products, or services available from them. You
                  assume sole responsibility and risk for your use of any such
                  websites or resources.
                </p>
              </div>
              <div>
                <h4>Compliance with Laws:</h4>
                <p id={classes.justify}>
                  As required by applicable law, if a Digistore Pay User makes a
                  purchase of INR 200,000 (Two Lakhs) or more, the User must
                  upload a scanned copy of their PAN card on the Platform within
                  48 hours of the purchase to activate the deal. Failure to do
                  so will result in the cancellation of the purchase, with no
                  responsibility on the part of Digistore Pay. The PAN card
                  submission is required only once; if it has been submitted
                  previously, it does not need to be resubmitted. If there is a
                  discrepancy between the User’s name and the name on the PAN
                  card, the order will be canceled, and the amount will be
                  refunded to the User’s credit card, bank account, or UPI
                  account according to the refund policy of the card issuer
                  bank. DiGi Suvidha assumes no responsibility in this regard.
                  <br />
                  Users must comply with all applicable laws, including but not
                  limited to the Foreign Exchange Management Act, 1999, and
                  related rules, the Customs Act, the Information Technology
                  Act, 2000 (as amended), the Prevention of Money Laundering
                  Act, 2002, the Foreign Contribution Regulation Act, 1976, the
                  Income Tax Act, 1961, and the Export Import Policy of the
                  Government of India, as relevant to their use of the Payment
                  Facility.
                  <br />
                  Nothing on the App constitutes, or is intended to constitute,
                  advice of any kind. All products sold or services purchased
                  through the App are governed by various state laws. If a
                  Seller or Digistore Pay is unable to deliver a product due to
                  state law implications, the Seller will either return or
                  credit the amount received in advance for the undelivered
                  product. There will be no compensation for samples, as they
                  are delivered free of cost.
                </p>
              </div>
              <div>
                <h4>Intellectual Property Rights:</h4>
                <p id={classes.justify}>
                  Unless otherwise indicated or expressly mentioned as
                  proprietary material owned by a third party, the Services
                  contain content to which Digistore Pay holds all intellectual
                  property rights. This includes, but is not limited to,
                  copyright, related rights, patents, utility models,
                  trademarks, trade names, service marks, designs, know-how,
                  trade secrets, inventions (whether patentable or not),
                  goodwill, source code, meta tags, databases, text, content,
                  graphics, icons, and hyperlinks ("Digistore Pay Content"). You
                  acknowledge and agree not to use, copy, imitate, reproduce, or
                  distribute any Digistore Pay Content without obtaining
                  authorization from Digistore Pay.
                  <br />
                  However, you retain ownership of and are solely responsible
                  for any Content that you provide or upload when using the
                  Services. This includes any text, data, information, images,
                  photographs, music, sound, video, or other materials you may
                  upload, transmit, or store while using our Services. You grant
                  DiGi Suvidha a non-exclusive, fully paid, royalty-free,
                  transferable, sub-licensable, worldwide license to use the
                  Content you post on or through the Service, subject to
                  Digistore Pay's Privacy Policy.
                  <br />
                  Some parts of the Service may be supported by advertising
                  revenue and may display advertisements and promotions. You
                  agree that Digistore Pay may place such advertisements and
                  promotions on the Service or in conjunction with your Content.
                  The manner, mode, and extent of such advertising and
                  promotions may change without specific notice to you. You
                  acknowledge that not all paid services, sponsored content, or
                  commercial communications may be explicitly identified as
                  such.
                </p>
              </div>
              <div>
                <h4>License:</h4>
                <p id={classes.justify}>
                  You acquire no rights or licenses in the Content other than
                  the limited right to access it on your mobile device or
                  computer. You are not permitted to download any Content from
                  the App/Website; you may only live stream it. Digistore Pay is
                  not responsible for any issues related to your internet
                  connection, including slow speeds or disruptions leading to
                  order rejections or payment deductions, nor for the quality of
                  the equipment you use to access the Service.
                </p>
              </div>
              <div>
                <h4>Limitation Of Liability:</h4>
                <p id={classes.justify}>
                  Under no circumstances shall Digistore Pay, its suppliers,
                  merchants, agents, directors, officers, employees,
                  representatives, successors, or assigns be liable to any user
                  for damages arising from the use, misuse, or reliance on the
                  platforms. This includes direct, special, punitive, indirect,
                  consequential, or incidental damages, or damages for loss of
                  profits, revenue, use, or data, whether based on warranty,
                  contract, intellectual property infringement, tort (including
                  negligence), or any other theory. This applies even if DiGi
                  Suvidha has been advised of the possibility of such damages,
                  connected with the use (or inability to use) the materials or
                  the internet generally, or reliance upon any material
                  contained in or accessed from the platforms.
                  <br />
                  Digistore Pay does not assume any legal liability or
                  responsibility for the accuracy, completeness, or usefulness
                  of any information, apparatus, product, service, or process
                  disclosed on the platforms or other material accessible from
                  the platforms.
                  <br />
                  Users assume all responsibility and risk for their use of the
                  platform and the internet generally. These limitations apply
                  notwithstanding any failure of the essential purpose of any
                  limited remedy and to the fullest extent permitted under
                  applicable law. In some jurisdictions, the exclusion or
                  limitation of liability for consequential or incidental
                  damages may not be allowed, so the above exclusions may not
                  apply to all users; in such cases, liability is limited to the
                  fullest extent permitted by law.
                  <br />
                  Notwithstanding anything to the contrary, the extent of
                  liability under all circumstances shall not exceed the
                  transaction or service fee received by Digistore Pay for the
                  disputed transaction from the user or merchant, as applicable.
                </p>
              </div>
              <div>
                <h4>Disclaimers And Limitations Of Liability:</h4>
                <p id={classes.justify}>
                  Digistore Pay shall not be liable for any indirect,
                  incidental, special, consequential, or punitive damages, or
                  any loss of profits, revenues, data, use, goodwill, or other
                  intangible losses resulting from: (i) your access to or use of
                  or inability to access or use the services; (ii) any conduct
                  or content of any third party on the services, including
                  without limitation, any defamatory, offensive, or illegal
                  conduct by other users or third parties; (iii) any content
                  obtained from the services; or (iv) unauthorized access, use,
                  or alteration of your transmissions or content. These
                  limitations apply to any theory of liability, whether based on
                  warranty, contract, statute, tort (including negligence), or
                  otherwise, even if Digistore Pay has been informed of the
                  possibility of such damage, and even if a remedy set forth
                  herein is found to have failed of its essential purpose.
                </p>
              </div>
              <div>
                <h4>Updates:</h4>
                <p id={classes.justify}>
                  Users are expected to regularly update the Digistore Pay app
                  to access the latest services and stay informed of any changes
                  in Digistore Pay's policies. By registering your phone number
                  with us, you consent to be contacted via phone calls, SMS,
                  and/or pop-up notifications regarding order, shipment, or
                  delivery updates. Failure to update the app may result in
                  Digistore Pay being unable to address any issues arising from
                  outdated information or services. Digistore Pay is not liable
                  for any consequences resulting from the failure to update the
                  app.
                </p>
              </div>
              <div>
                <h4>Refund & Cancellation Policy:</h4>
                <div id={classes.justify}>
                  <ol type="i" id={classes.justify}>
                    <li>
                      Offline Vendors: Digistore Pay is not obligated to refund
                      any amount paid by you under this agreement. Refunds are
                      governed entirely by the Cancellation & Refund Policy
                      posted on the Digistore Pay app.
                    </li>
                    <li>
                      Online Vendors: Similarly, Digistore Pay is not
                      responsible for any refunds under this agreement. Refund
                      policies are governed by the Cancellation & Refund Policy
                      available on the Digistore Pay app.
                    </li>
                  </ol>
                </div>
              </div>
              <div>
                <h4>User Covenant:</h4>
                <p id={classes.justify}>
                  You agree to purchase services and goods only from registered
                  Digistore Pay merchants, whether online or offline. Any
                  transactions outside of this network are not covered by DiGi
                  Suvidha’s policies.
                </p>
              </div>
              <div>
                <h4>Indemnification:</h4>
                <p id={classes.justify}>
                  You agree to indemnify, defend, and hold harmless Digistore
                  Pay, its associates, and partners from any losses,
                  liabilities, claims, damages, costs, and expenses, including
                  legal fees, arising from breaches of law or any rights of
                  users, including but not limited to intellectual property
                  rights, or non-performance of any representations, warranties,
                  covenants, or obligations under these terms.
                </p>
              </div>
              <div>
                <h4>Payment:</h4>
                <p id={classes.justify}>
                  Digistore Pay is not liable for any loss or damage resulting
                  from issues such as lack of authorization for transactions,
                  exceeding pre-set limits agreed upon with banks, payment
                  issues, or transaction declines.
                  <br />
                  All payments for purchases made on the app must be in Indian
                  Rupees. Transactions in other currencies are not facilitated
                  by the app.
                </p>
              </div>
              <div>
                <h4>Relationship:</h4>
                <p id={classes.justify}>
                  Transactions, transaction prices are governed by
                  principal-to-principal bipartite contractual obligations
                  between the Buyer and Seller. The payment facility provided by
                  Digistore Pay is merely a tool to facilitate the completion of
                  these transactions. The use of this payment facility does not
                  render DiGi Suvidha, its associates, or partners liable for
                  non-delivery, non-receipt, non-payment, damage, breach of
                  representations and warranties, non-provision of after-sales
                  or warranty services, or fraud related to the products listed
                  on and purchased through the app.
                  <br />
                  You specifically authorize DiGi Suvidha and its service
                  providers to collect, process, facilitate, and remit payments
                  and/or the transaction price electronically to and from other
                  users in respect of transactions through the relevant payment
                  system ("Payment Facility"). Your relationship with DiGi
                  Suvidha is on a principal-to-principal basis, and by accepting
                  these Terms, you agree that DiGi Suvidha acts as an
                  independent contractor for all purposes. DiGi Suvidha does not
                  control or guarantee the products listed on the app that are
                  paid for using the Payment Facility and does not ensure that a
                  Buyer or Seller will complete a transaction.
                  <br />
                  For Credit/Debit card/Netbanking transactions, you understand,
                  accept, and agree that the Payment Facility provided by
                  Digistore Pay is neither a banking nor financial service but a
                  facilitator that provides an electronic, automated online
                  channel for electronic payment, collection, and remittance
                  through existing authorized banking infrastructure payment
                  gateway networks. By providing this Payment Facility, DiGi
                  Suvidha, its associates, and partners are neither acting as
                  trustees nor in a fiduciary capacity with respect to the
                  transaction or the transaction price.
                </p>
              </div>
              <div>
                <h4>Prohibited Activities:</h4>
                <div id={classes.justify}>
                  You agree that you shall not host, display, upload, modify,
                  publish, transmit, update or share any information on the
                  App/Site, that:
                  <ul id={classes.justify}>
                    <li>
                      belongs to another person and to which you do not have any
                      right to; 
                    </li>
                    <li>
                      is grossly harmful, harassing, blasphemous, defamatory,
                      obscene, pornographic, paedophilic, libellous, invasive of
                      another's privacy, hateful, or racially, ethnically
                      objectionable, disparaging, relating or encouraging money
                      laundering or gambling, or otherwise unlawful in any
                      manner whatever;
                    </li>
                    <li>harm minors in any way;</li>
                    <li>
                      infringes any patent, trademark, copyright or other
                      proprietary rights;
                    </li>
                    <li>violates any law for the time being in force;</li>
                    <li>
                      deceives or misleads the addressee about the origin of
                      such messages or communicates any information which is
                      grossly offensive or menacing in nature; 
                    </li>
                    <li>impersonate another person;</li>
                    <li>
                      contains software viruses or any other computer code,
                      files or programs designed to interrupt, destroy or limit
                      the functionality of any computer resource; 
                    </li>
                    <li>
                      Abuse, harass, threaten, defame, disillusion, erode,
                      abrogate, demean or otherwise violate the legal rights of
                      others; 
                    </li>
                    <li>
                      Engage in any activity that interferes with or disrupts
                      access to the Website or the Services (or the servers and
                      networks which are connected to the Website); 
                    </li>
                    <li>
                      Impersonate any person or entity, or falsely state or
                      otherwise misrepresent Your affiliation with a person or
                      entity;
                    </li>
                    <li>
                      Publish, post, disseminate, any information which is
                      grossly harmful, harassing, blasphemous, defamatory,
                      obscene, pornographic, paedophilic, libellous, invasive of
                      another's privacy, hateful, or racially, ethnically
                      objectionable, disparaging, relating or encouraging money
                      laundering or gambling, or otherwise unlawful in any
                      manner whatever; or unlawfully threatening or unlawfully
                      harassing including but not limited to "indecent
                      representation of women" within the meaning of the
                      Indecent Representation of Women (Prohibition) Act, 1986;
                    </li>
                    <li>
                      Directly or indirectly, offer, attempt to offer, trade or
                      attempt to trade in any item, the dealing of which is
                      prohibited or restricted in any manner under the
                      provisions of any applicable law, rule, regulation or
                      guideline for the time being in force. 
                    </li>
                    <li>
                      threatens the unity, integrity, defence, security or
                      sovereignty of India, friendly relations with foreign
                      states, or public order or causes incitement to the
                      commission of any cognisable offence or prevents
                      investigation of any offence or is insulting any other
                      nation. 
                    </li>
                  </ul>
                  Any Content and or comment uploaded by you, shall be subject
                  to relevant Indian laws and may be disabled, or and may be
                  subject to investigation under appropriate laws. Furthermore,
                  if you are found to be in non-compliance with the laws and
                  regulations, these terms, or the privacy policy of the
                  App/Site, the Company shall have the right to immediately
                  terminate/block your access and usage of the App/Site and the
                  Company shall have the right to immediately remove any
                  noncompliant Content and or comment, uploaded by you and shall
                  further have the right to take recourse to such remedies as
                  would be available to the Company under the applicable laws. 
                </div>
              </div>
              <div>
                <h4>Merchant's Obligations:</h4>
                <p id={classes.justify}>
                  As a Merchant, whether offline or online, registered on the
                  Digistore Pay platform, you are allowed to promote or list any
                  Product(s)/Service(s) for sale in accordance with the policies
                  incorporated by reference in these Terms.
                  <ul>
                    <li>
                      Legal Authorization: You must be legally authorized to
                      sell the Product(s)/Service(s) listed on the Digistore Pay
                      platform.
                    </li>
                    <li>
                      Intellectual Property Compliance: You must ensure that the
                      listed Products/Services do not infringe upon intellectual
                      property rights, trade secrets, or any other proprietary,
                      publicity, or privacy rights of third parties.
                    </li>
                    <li>
                      Accurate Product Listings: Listings may only include text
                      descriptions, graphics, and pictures that accurately
                      describe your Product/Service for sale. All listed
                      Products must be categorized appropriately on the
                      Digistore Pay app.
                    </li>
                    <li>
                      Compliance with Merchant Terms: In addition to these
                      Terms, you agree to comply with the Merchant Terms posted
                      on the Digistore Pay platform, which are incorporated
                      herein by reference.
                    </li>
                  </ul>
                </p>
              </div>
              <div>
                <h4>Digistore Pay User's Arrangement With Issuing Bank:</h4>
                <ul id={classes.justify}>
                  <li>
                    Payment Instrument Processing: All valid credit, debit, and
                    cash cards, along with other payment instruments, are
                    processed through an appropriate payment gateway or payment
                    system infrastructure. These transactions are governed by
                    the terms and conditions set between the Digistore Pay User
                    and the respective issuing bank or payment instrument
                    issuing company.
                  </li>
                  <li>
                    Online Bank Transfers: Online bank transfers from valid bank
                    accounts are facilitated using the payment gateway provided
                    by the respective issuing bank. These transactions are also
                    governed by the terms and conditions agreed upon between the
                    Digistore Pay User and the respective issuing bank.
                  </li>
                  <li>
                    DiGital Loan Financing: Digistore Pay Users availing DiGital
                    loan financing through partner Merchant Bank(s), in
                    accordance with the Customer Terms of the Digistore Pay
                    platform, may make payments for purchased products. The
                    payment is subject to a specified monetary limit for the
                    User, determined by the Partner Merchant’s bank account and
                    facilitated through DiGi Suvidha ("Transaction Amount").
                  </li>
                  <li>
                    Monetary Limits and Approval: Digistore Pay, along with the
                    Partner Merchant’s bank, reserves the right to modify,
                    amend, or restrict the monetary limit or approve/reject
                    funds at its sole discretion. These decisions can be made
                    for any reason and are applicable to each Digistore Pay User
                    individually.
                  </li>
                </ul>
              </div>
              <div>
                <h4>Jurisdictional Issues in India:</h4>
                <p id={classes.justify}>
                  Unless otherwise stated, all services, products, and materials
                  offered through Digistore Pay are solely intended for use and
                  sale within India. Digistore Pay makes no representation or
                  warranty that the materials, products, or services available
                  through its platform are appropriate or available for use in
                  jurisdictions outside of India. Users who choose to access
                  Digistore Pay from locations outside of India do so at their
                  own risk and initiative.
                </p>
              </div>
              <div>
                <h4>Trademark, Copyright, and Restrictions:</h4>
                <p id={classes.justify}>
                  The Digistore Pay app services are controlled and operated by
                  Digistore Pay, its partners, and associates. Products and
                  services are offered for sale or ordering by the respective
                  Merchants through our platform. All materials on this
                  app—including images, illustrations, audio clips, and video
                  clips—are protected by copyrights, trademarks, and other
                  intellectual property rights.
                  <br />
                  All content included on the app, such as text, graphics,
                  logos, button icons, images, audio clips, DiGital downloads,
                  data compilations, and software, is the property of Digistore
                  Pay or its Merchants, unless otherwise specified or owned by a
                  third party and protected by applicable copyright laws. Any
                  other content not owned by Digistore Pay that appears on the
                  app is the property of its respective owners. All software
                  used on this app is the property of Digistore Pay and is
                  protected by applicable copyright laws. Unauthorized copying
                  or reproduction of any such material is strictly prohibited by
                  law.
                  <br />
                  The Digistore Pay logo and other marks indicated on the app
                  are trademarks of DiGi Suvidha Private Limited. Other
                  Digistore Pay graphics, logos, page headers, button icons,
                  scripts, and service names are trademarks or trade dress of
                  Digistore Pay. These trademarks and trade dress may not be
                  used in connection with any product or service that is not
                  provided by DiGi Suvidha, in any manner that is likely to
                  cause confusion among users, or in any manner that disparages
                  or discredits DiGi Suvidha. All other trademarks not owned by
                  Digistore Pay that appear on this app are the property of
                  their respective owners.
                  <br />
                  Materials on the app are provided solely for your personal,
                  non-commercial use. You must not copy, reproduce, republish,
                  upload, post, transmit, or distribute any such material in any
                  way, including by email or other electronic means, whether
                  directly or indirectly. You are also prohibited from assisting
                  others in such activities. Without prior written consent from
                  the owner, modifying the materials, using them on any other
                  website or networked computer environment, or using the
                  materials for any purpose other than personal, non-commercial
                  use is a violation of copyrights, trademarks, and other
                  proprietary rights, and is strictly prohibited. Any use for
                  which you receive any remuneration, whether monetary or
                  otherwise, is considered commercial use for the purposes of
                  this clause.
                </p>
              </div>
              <div>
                <h4>Trademark Complaint:</h4>
                <p id={classes.justify}>
                  Digistore Pay respects the intellectual property rights of
                  others. If you believe that your trademark has been infringed,
                  you can submit your complaint by writing to Digistore Pay at{" "}
                  <Link className={classes.linkTags}>
                    info@digistorepay.com
                  </Link>
                  .
                </p>
              </div>
              <div>
                <h4>No Waiver:</h4>
                <p id={classes.justify}>
                  Unless otherwise expressly stated, any failure or delay by
                  Digistore Pay to exercise a right or remedy under these terms
                  shall not be deemed a waiver of that right or remedy, nor
                  shall it constitute a waiver of any other rights or remedies.
                  Additionally, any single or partial exercise of any right or
                  remedy will not prevent the further exercise of that right or
                  the exercise of any other right or remedy.
                </p>
              </div>
              <div>
                <h4>Force Majeure:</h4>
                <p id={classes.justify}>
                  Digistore Pay shall not be held responsible or liable for any
                  delay or failure to perform its obligations under this
                  Agreement (except for payment obligations) due to unforeseen
                  circumstances or events beyond its reasonable control, and
                  without its fault or negligence. Such events may include, but
                  are not limited to, acts of God, war, riots, embargoes,
                  strikes, lockouts, pandemics, acts of governmental
                  authorities, delays in obtaining licenses, rejection of
                  applications under laws, server malfunctions, telephone
                  connection failures, malware or virus attacks on Digistore
                  Pay’s servers, power failures, fires, or floods.
                </p>
              </div>
              <div>
                <h4>Non -exclusivity:</h4>
                <p id={classes.justify}>
                  It is agreed and clarified that the arrangement set out by
                  these T&C between Digistore Pay and the Digistore Pay Users is
                  on non-exclusive basis.
                </p>
              </div>
              <div>
                <h4>Non-Solicitation:</h4>
                <p id={classes.justify}>
                  The Digistore Pay User warrants that they shall not, either
                  directly or indirectly, solicit for employment, offer
                  employment to, or enter into any contract of services with any
                  person employed by Digistore Pay.
                  <br />
                  These Terms shall be governed by and construed in accordance
                  with the laws of India.
                  <br />
                  The Terms herein shall apply equally to both the singular and
                  plural form of the terms defined. Whenever the context may
                  require, any pronoun shall include the corresponding
                  masculine, feminine, and neuter. The words "include",
                  "includes", and "including" shall be deemed to be followed by
                  the phrase "without limitation". Unless otherwise specified,
                  the terms "herein", "hereof", "hereto", "hereunder" and words
                  of similar import refer to the Terms as a whole. Capitalized
                  words used throughout these Terms shall have the meaning that
                  is readily inferable from the context or as commonly
                  understood in commercial use.
                </p>
              </div>
              <div>
                <h4>Headings:</h4>
                <p id={classes.justify}>
                  The headings and subheadings in these Terms are provided
                  solely for convenience and ease of reference. They are not
                  intended to describe, interpret, define, or limit the scope,
                  extent, or intent of these Terms, your rights to use the App,
                  or any section or pages of the App or any linked sites in any
                  way.
                </p>
              </div>
              <div>
                <h4>Assignment:</h4>
                <p id={classes.justify}>
                  The Digistore Pay User shall not assign this Agreement to any
                  third party under any circumstances. However, Digistore Pay
                  reserves the right to assign this Agreement to any party
                  without requiring prior notice to the Digistore Pay User.
                </p>
              </div>
              <div>
                <h4>Severability:</h4>
                <p id={classes.justify}>
                  Severability: If any provision of these Terms is found to be
                  invalid or unenforceable in whole or in part, such invalidity
                  or unenforceability shall apply only to that specific
                  provision or part of the provision. The remaining provisions
                  of these Terms, and any other parts of the invalid or
                  unenforceable provision, shall continue to be in full force
                  and effect.
                </p>
              </div>
              <div>
                <h4>Report Abuse:</h4>
                <p id={classes.justify}>
                  As per these Terms, Digistore Pay Users are solely responsible
                  for all material or content uploaded onto the App. Digistore
                  Pay does not review or verify the content before it appears on
                  the App and does not endorse or vouch for any content posted
                  or uploaded by users. Users may be held legally liable for
                  their content and could be accountable if their material
                  includes, for example, defamatory comments or content
                  protected by copyright or trademark.
                  <br />
                  If you encounter any abuse or violations of these Terms,
                  please report them to Digistore Pay.
                </p>
              </div>
              <div>
                <h4>Unauthorized Charges on Your Card:</h4>
                <p id={classes.justify}>
                  If you notice charges on your credit/debit card for purchases
                  made through the App that you did not authorize or do not
                  recognize, please first check with family members or
                  colleagues who may have been authorized to make purchases on
                  your behalf. If, after doing so, you still cannot identify the
                  charge, please report the unauthorized purchase to Digistore
                  Pay within 7 days of the transaction. This will enable
                  Digistore Pay to initiate an investigation into the issue.
                </p>
              </div>
              <div>
                <h4>Mispricing:</h4>
                <p id={classes.justify}>
                  Despite our best efforts to ensure accuracy, some Products in
                  our catalog may be mispriced. As part of our shipping
                  procedures, we verify the prices of all Products.
                  <ul>
                    <li>
                      If the correct price (MRP) of a Product is lower than the
                      price stated on our App, we will charge you the lower
                      amount and refund the excess amount.
                    </li>
                    <li>
                      If the correct price (MRP) of a Product is higher than the
                      stated price, we will cancel your order and notify you of
                      the cancellation.
                    </li>
                  </ul>
                  This approach ensures that any discrepancies in pricing are
                  addressed promptly and fairly.
                </p>
              </div>
              <div>
                <h4>Profanity Policy:</h4>
                <p id={classes.justify}>
                  Digistore Pay prohibits the use of language that is obscene,
                  racist, hateful, or otherwise disparaging in any manner
                  whatsoever. This policy applies to text within listings, on
                  merchant pages, and all other areas of the site that other
                  Users may view. If profane words are part of a title for an
                  item being sold, Sellers are allowed to 'blur' out the bulk of
                  the offending word with asterisks.
                  <br />
                  If any feedback comment or communication between Digistore Pay
                  Users through the App or via email contains profane language,
                  please submit a request for action or removal. Disciplinary
                  action may result in either an indefinite suspension of a
                  User's account, a temporary suspension, or a formal warning.
                  Digistore Pay will consider the circumstances of an alleged
                  policy violation and the User's trading records before taking
                  action. Violations may result in a range of actions, including
                  limits placed on account privileges, loss of special status,
                  and account suspension.
                </p>
              </div>
              <div>
                <h4>Grievance Officer:</h4>
                <p id={classes.justify}>
                  In accordance with the Information Technology Act, 2000 and
                  the rules made thereunder, the name and contact details of the
                  Grievance Officer are provided below:
                </p>
              </div>
              <div>
                <h4>Contact info below:</h4>
                <p>
                  DiGi Suvidha Private Limited, <br />
                  First Floor,
                  <br />
                  Zam Zam Plaza Above More Super Market,
                  <br />
                  Pala Road, Ettumanoor,
                  <br />
                  Kottayam, Kerala - 686631
                </p>
                <h4>Contact Us:</h4>
                <p>
                  Email:{" "}
                  <Link className={classes.linkTags}>
                    info@digistorepay.com
                  </Link>
                  <br />
                  Phone: +918606172633
                  <br />
                  Time: Mon - Sat (9:30 AM - 05:30PM)
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default TermsOfUse;
